/**
 * Dados de exemplo para as telas.
 *
 * IMPORTANTE PARA O BACKEND: nada aqui e persistido — e tudo estatico,
 * so para dar forma a UI. Cada export abaixo deve virar uma chamada de
 * API com o mesmo formato definido em `types.ts`, sem alterar as telas.
 */

import type {
  Banco,
  Cliente,
  Compromisso,
  ContaPagar,
  ContaReceber,
  Empresa,
  Produto,
  Venda,
} from './types'

export const empresa: Empresa = {
  id: 'emp-1',
  razaoSocial: 'Mercearia Sol Nascente LTDA',
  nomeFantasia: 'Mercearia Sol Nascente',
  cnpj: '12.345.678/0001-90',
  inscricaoEstadual: '907.123.456.789',
  inscricaoMunicipal: '1.234.567-8',
  ramoAtividade: 'Comercio varejista de alimentos',
  ddd: '41',
  celular: '99876-5432',
  email: 'contato@solnascente.com.br',
  endereco: {
    cep: '80010-010',
    logradouro: 'Rua das Flores',
    numero: '482',
    complemento: 'Loja 2',
    bairro: 'Centro',
    cidade: 'Curitiba',
    uf: 'PR',
  },
  comissaoHabilitada: true,
  comissaoPercentual: 3,
}

export const clientes: Cliente[] = [
  {
    id: 'cli-1',
    nome: 'Joana Ribeiro',
    documento: '123.456.789-00',
    tipoPessoa: 'fisica',
    ddd: '41',
    celular: '99123-4567',
    email: 'joana@email.com',
    endereco: {
      cep: '80020-100',
      logradouro: 'Av. Sete de Setembro',
      numero: '1200',
      bairro: 'Centro',
      cidade: 'Curitiba',
      uf: 'PR',
    },
    ultimaCompra: '2026-08-24',
    totalCompras: 34,
    valorTotal: 4820.5,
  },
  {
    id: 'cli-2',
    nome: 'Padaria Sol LTDA',
    documento: '98.765.432/0001-10',
    tipoPessoa: 'juridica',
    ddd: '41',
    celular: '99888-1122',
    email: 'compras@padariasol.com.br',
    endereco: {
      cep: '82010-200',
      logradouro: 'Rua Xavier da Silva',
      numero: '88',
      bairro: 'Bacacheri',
      cidade: 'Curitiba',
      uf: 'PR',
    },
    ultimaCompra: '2026-08-22',
    totalCompras: 112,
    valorTotal: 28940.0,
  },
  {
    id: 'cli-3',
    nome: 'Marcos Dias',
    documento: '321.654.987-11',
    tipoPessoa: 'fisica',
    ddd: '41',
    celular: '99555-7788',
    endereco: {
      cep: '81530-000',
      logradouro: 'Rua Prof. Algacyr Munhoz',
      numero: '45',
      bairro: 'Jardim das Americas',
      cidade: 'Curitiba',
      uf: 'PR',
    },
    ultimaCompra: '2026-08-19',
    totalCompras: 8,
    valorTotal: 1245.9,
  },
  {
    id: 'cli-4',
    nome: 'Restaurante Boa Mesa',
    documento: '45.678.912/0001-33',
    tipoPessoa: 'juridica',
    ddd: '41',
    celular: '99777-3344',
    email: 'financeiro@boamesa.com.br',
    endereco: {
      cep: '80530-000',
      logradouro: 'Av. Batel',
      numero: '1750',
      bairro: 'Batel',
      cidade: 'Curitiba',
      uf: 'PR',
    },
    ultimaCompra: '2026-06-02',
    totalCompras: 57,
    valorTotal: 19870.4,
  },
  {
    id: 'cli-5',
    nome: 'Carla Menezes',
    documento: '789.123.456-22',
    tipoPessoa: 'fisica',
    ddd: '41',
    celular: '99222-9900',
    endereco: {
      cep: '80440-000',
      logradouro: 'Rua Comendador Araujo',
      numero: '310',
      bairro: 'Centro',
      cidade: 'Curitiba',
      uf: 'PR',
    },
    ultimaCompra: '2026-03-11',
    totalCompras: 3,
    valorTotal: 412.3,
  },
]

export const produtos: Produto[] = [
  {
    id: 'prod-1',
    codigo: 'CAF500',
    descricao: 'Cafe torrado e moido 500g',
    ean: '7891000315507',
    ncm: '0901.21.00',
    categoria: 'Mercearia',
    fornecedor: 'Torrefacao Aurora',
    precoCusto: 14.2,
    precoVenda: 21.9,
    estoque: 4,
    estoqueMinimo: 12,
    diasSemVenda: 0,
  },
  {
    id: 'prod-2',
    codigo: 'ACU1KG',
    descricao: 'Acucar mascavo 1kg',
    ean: '7896002301459',
    ncm: '1701.13.00',
    categoria: 'Mercearia',
    fornecedor: 'Engenho Doce',
    precoCusto: 8.4,
    precoVenda: 12.9,
    estoque: 2,
    estoqueMinimo: 10,
    diasSemVenda: 1,
  },
  {
    id: 'prod-3',
    codigo: 'LEI1L',
    descricao: 'Leite integral 1L',
    ean: '7891000053508',
    ncm: '0401.20.10',
    categoria: 'Laticinios',
    fornecedor: 'Laticinios Campo Verde',
    precoCusto: 3.8,
    precoVenda: 5.99,
    estoque: 6,
    estoqueMinimo: 24,
    diasSemVenda: 0,
  },
  {
    id: 'prod-4',
    codigo: 'FIL103',
    descricao: 'Filtro de papel n103',
    ean: '7891234000112',
    ncm: '4823.20.90',
    categoria: 'Utilidades',
    fornecedor: 'Torrefacao Aurora',
    precoCusto: 5.1,
    precoVenda: 8.9,
    estoque: 9,
    estoqueMinimo: 15,
    diasSemVenda: 2,
  },
  {
    id: 'prod-5',
    codigo: 'BIS200',
    descricao: 'Biscoito integral 200g',
    ean: '7896005412305',
    ncm: '1905.31.00',
    categoria: 'Mercearia',
    fornecedor: 'Alimentos Boa Safra',
    precoCusto: 4.6,
    precoVenda: 7.5,
    estoque: 48,
    estoqueMinimo: 20,
    diasSemVenda: 63,
  },
  {
    id: 'prod-6',
    codigo: 'AZE500',
    descricao: 'Azeite extra virgem 500ml',
    ean: '7896102503012',
    ncm: '1509.10.00',
    categoria: 'Mercearia',
    fornecedor: 'Importadora Oliva',
    precoCusto: 22.9,
    precoVenda: 39.9,
    estoque: 31,
    estoqueMinimo: 10,
    diasSemVenda: 4,
  },
]

export const vendas: Venda[] = [
  {
    id: 'ven-1',
    numero: '1842',
    clienteId: 'cli-1',
    clienteNome: 'Joana Ribeiro',
    data: '2026-08-24T14:32:00',
    itens: [
      {
        produtoId: 'prod-1',
        descricao: 'Cafe torrado e moido 500g',
        quantidade: 2,
        precoUnitario: 21.9,
        desconto: 0,
      },
      {
        produtoId: 'prod-4',
        descricao: 'Filtro de papel n103',
        quantidade: 1,
        precoUnitario: 8.9,
        desconto: 0,
      },
      {
        produtoId: 'prod-2',
        descricao: 'Acucar mascavo 1kg',
        quantidade: 3,
        precoUnitario: 12.9,
        desconto: 4.5,
      },
    ],
    subtotal: 91.4,
    desconto: 4.5,
    total: 86.9,
    formaPagamento: 'pix',
    status: 'concluida',
    nota: 'nfce',
    custoTotal: 56.6,
    imposto: 3.12,
    tarifaCartao: 0,
    valorLiquido: 83.78,
  },
  {
    id: 'ven-2',
    numero: '1841',
    clienteId: null,
    clienteNome: 'Venda avulsa',
    data: '2026-08-24T13:58:00',
    itens: [
      {
        produtoId: 'prod-6',
        descricao: 'Azeite extra virgem 500ml',
        quantidade: 1,
        precoUnitario: 39.9,
        desconto: 0,
      },
    ],
    subtotal: 89.0,
    desconto: 0,
    total: 89.0,
    formaPagamento: 'credito',
    status: 'concluida',
    nota: 'nfce',
    custoTotal: 51.4,
    imposto: 3.2,
    tarifaCartao: 3.12,
    valorLiquido: 82.68,
  },
  {
    id: 'ven-3',
    numero: '1840',
    clienteId: 'cli-3',
    clienteNome: 'Marcos Dias',
    data: '2026-08-24T11:20:00',
    itens: [],
    subtotal: 412.5,
    desconto: 0,
    total: 412.5,
    formaPagamento: 'dinheiro',
    status: 'concluida',
    nota: 'nfce',
    custoTotal: 268.0,
    imposto: 14.8,
    tarifaCartao: 0,
    valorLiquido: 397.7,
  },
  {
    id: 'ven-4',
    numero: '1839',
    clienteId: 'cli-2',
    clienteNome: 'Padaria Sol LTDA',
    data: '2026-08-23T17:05:00',
    itens: [],
    subtotal: 156.2,
    desconto: 0,
    total: 156.2,
    formaPagamento: 'debito',
    status: 'concluida',
    nota: 'nfce',
    custoTotal: 98.4,
    imposto: 5.6,
    tarifaCartao: 1.56,
    valorLiquido: 149.04,
  },
  {
    id: 'ven-5',
    numero: '1838',
    clienteId: 'cli-4',
    clienteNome: 'Restaurante Boa Mesa',
    data: '2026-08-23T09:44:00',
    itens: [],
    subtotal: 78.4,
    desconto: 0,
    total: 78.4,
    formaPagamento: 'carteira',
    status: 'cancelada',
    nota: 'sem_nota',
    custoTotal: 0,
    imposto: 0,
    tarifaCartao: 0,
    valorLiquido: 0,
  },
]

export const bancos: Banco[] = [
  {
    id: 'bco-1',
    nome: 'Banco do Brasil',
    agencia: '1234-5',
    conta: '98765-4',
    saldo: 11905.4,
    integrado: true,
    ultimaConciliacao: '2026-08-24T08:00:00',
  },
  {
    id: 'bco-2',
    nome: 'Nubank PJ',
    agencia: '0001',
    conta: '12345678-9',
    saldo: 8420.15,
    integrado: true,
    ultimaConciliacao: '2026-08-24T08:00:00',
  },
  {
    id: 'bco-3',
    nome: 'Caixa Economica',
    agencia: '4321',
    conta: '00123-7',
    saldo: 2310.0,
    integrado: false,
    ultimaConciliacao: null,
  },
]

export const contasPagar: ContaPagar[] = [
  {
    id: 'cp-1',
    fornecedor: 'Torrefacao Aurora',
    planoContasId: 'pc-1',
    planoContasNome: 'Fornecedores',
    bancoId: 'bco-1',
    bancoNome: 'Banco do Brasil',
    vencimento: '2026-08-24',
    valor: 1240.0,
    valorPago: 0,
    descricao: 'Pedido 4471',
    status: 'aberto',
  },
  {
    id: 'cp-2',
    fornecedor: 'Imobiliaria Centro',
    planoContasId: 'pc-2',
    planoContasNome: 'Aluguel',
    bancoId: 'bco-1',
    bancoNome: 'Banco do Brasil',
    vencimento: '2026-08-27',
    valor: 3800.0,
    valorPago: 0,
    descricao: 'Aluguel de agosto',
    status: 'aberto',
  },
  {
    id: 'cp-3',
    fornecedor: 'Copel',
    planoContasId: 'pc-3',
    planoContasNome: 'Energia e agua',
    bancoId: 'bco-1',
    bancoNome: 'Banco do Brasil',
    vencimento: '2026-09-01',
    valor: 742.3,
    valorPago: 0,
    descricao: 'Conta de energia',
    status: 'aberto',
  },
  {
    id: 'cp-4',
    fornecedor: 'Laticinios Campo Verde',
    planoContasId: 'pc-1',
    planoContasNome: 'Fornecedores',
    bancoId: 'bco-2',
    bancoNome: 'Nubank PJ',
    vencimento: '2026-08-18',
    valor: 680.0,
    valorPago: 0,
    descricao: 'Pedido 4468',
    status: 'vencido',
  },
  {
    id: 'cp-5',
    fornecedor: 'Alimentos Boa Safra',
    planoContasId: 'pc-1',
    planoContasNome: 'Fornecedores',
    bancoId: 'bco-2',
    bancoNome: 'Nubank PJ',
    vencimento: '2026-08-20',
    valor: 1560.0,
    valorPago: 800.0,
    descricao: 'Pedido 4465',
    status: 'parcial',
  },
  {
    id: 'cp-6',
    fornecedor: 'Contabilidade Prisma',
    planoContasId: 'pc-4',
    planoContasNome: 'Folha de pagamento',
    bancoId: 'bco-2',
    bancoNome: 'Nubank PJ',
    vencimento: '2026-08-10',
    valor: 890.0,
    valorPago: 890.0,
    descricao: 'Honorarios de agosto',
    status: 'pago',
  },
]

export const contasReceber: ContaReceber[] = [
  {
    id: 'cr-1',
    clienteId: 'cli-2',
    clienteNome: 'Padaria Sol LTDA',
    bancoId: 'bco-1',
    bancoNome: 'Banco do Brasil',
    emissao: '2026-08-10',
    vencimento: '2026-08-25',
    referente: 'Pedido 8891',
    tipo: 'credito',
    valor: 4820.0,
    valorRecebido: 0,
    status: 'aberto',
  },
  {
    id: 'cr-2',
    clienteId: 'cli-4',
    clienteNome: 'Restaurante Boa Mesa',
    bancoId: 'bco-1',
    bancoNome: 'Banco do Brasil',
    emissao: '2026-08-01',
    vencimento: '2026-08-16',
    referente: 'Pedido 8874',
    tipo: 'credito',
    valor: 2310.5,
    valorRecebido: 0,
    status: 'vencido',
  },
  {
    id: 'cr-3',
    clienteId: 'cli-1',
    clienteNome: 'Joana Ribeiro',
    bancoId: 'bco-2',
    bancoNome: 'Nubank PJ',
    emissao: '2026-08-24',
    vencimento: '2026-08-24',
    referente: 'Venda 1842',
    tipo: 'pix',
    valor: 86.9,
    valorRecebido: 86.9,
    status: 'pago',
  },
  {
    id: 'cr-4',
    clienteId: 'cli-2',
    clienteNome: 'Padaria Sol LTDA',
    bancoId: 'bco-2',
    bancoNome: 'Nubank PJ',
    emissao: '2026-08-05',
    vencimento: '2026-09-05',
    referente: 'Pedido 8880',
    tipo: 'debito',
    valor: 6740.0,
    valorRecebido: 3000.0,
    status: 'parcial',
  },
  {
    id: 'cr-5',
    clienteId: 'cli-3',
    clienteNome: 'Marcos Dias',
    bancoId: 'bco-1',
    bancoNome: 'Banco do Brasil',
    emissao: '2026-08-19',
    vencimento: '2026-09-19',
    referente: 'Venda 1840',
    tipo: 'carteira',
    valor: 412.5,
    valorRecebido: 0,
    status: 'aberto',
  },
]

export const compromissos: Compromisso[] = [
  {
    id: 'ag-1',
    titulo: 'Cobrar Restaurante Boa Mesa',
    data: '2026-08-24',
    hora: '09:00',
    tipo: 'cobranca',
    clienteNome: 'Restaurante Boa Mesa',
    concluido: true,
  },
  {
    id: 'ag-2',
    titulo: 'Pagar Torrefacao Aurora',
    data: '2026-08-24',
    hora: '14:00',
    tipo: 'pagamento',
    concluido: false,
  },
  {
    id: 'ag-3',
    titulo: 'Entrega Padaria Sol',
    data: '2026-08-25',
    hora: '08:30',
    tipo: 'entrega',
    clienteNome: 'Padaria Sol LTDA',
    concluido: false,
  },
  {
    id: 'ag-4',
    titulo: 'Reuniao com contador',
    data: '2026-08-26',
    hora: '16:00',
    tipo: 'reuniao',
    concluido: false,
  },
  {
    id: 'ag-5',
    titulo: 'Aluguel do ponto',
    data: '2026-08-27',
    hora: '10:00',
    tipo: 'pagamento',
    concluido: false,
  },
]

/** Ramos de atividade oferecidos no cadastro da empresa. */
export const ramosAtividade = [
  'Comercio varejista de alimentos',
  'Restaurante e lanchonete',
  'Moda e vestuario',
  'Saude e bem-estar',
  'Casa e construcao',
  'Servicos em geral',
]
